### ISSUE TITLE
Storage Class and Function Calls Have Same Colour

### ISSUE THREAD

**Issue by elyobo** [patstockwell/vim-monokai-tasty#20]
This is possibly a personal preference thing, but given how frequently both of these occur I think it would be more useful to differentiate in colours, not just in italics, between storage classes like `const`, `let`, `var`, and function calls.

Currently they're almost identical.

```
call Highlight("StorageClass", s:light_blue, s:none, s:italic)
call Highlight("jsFuncCall", s:light_blue, s:none, s:none)
```

Personally I've switched strings to be italic green, so used the yellow for storage class instead.

**Comment by patstockwell** [comment]
Hi @elyobo, The colour choices for each of the tokens reflect the sublime text implementation of monokai. You are probably right when you say that storage classes and the function keyword could be more easily distinguished with colour, but then others who use this library because they like the similarity with sublime, might not agree.
Feel free to fork the repository and update the colours to suit your needs.
Thanks for the feedback! :)

**Comment by elyobo** [comment]
Thanks @patstockwell, makes sense.  Fork already in place and customised to my own preferences, thanks for your work in providing this :)
