### ISSUE TITLE
Better colors for HTML attributes

### ISSUE THREAD

**Issue by dubst3pp4** [patstockwell/vim-monokai-tasty#37]
At first many thanks for your great color scheme :+1: 

Compared to other colorschemes I recognized, that HTML attributes are hard to read:

Here is a screenshot of vim-monokai-tasty:
![Bildschirmfoto von 2021-09-20 10-28-59](https://user-images.githubusercontent.com/2373731/133975257-a908f4c0-377d-4163-b1fa-a83c1a308e1c.png)

and a screenshot compared to [night-owl](https://github.com/haishanh/night-owl.vim) colorscheme:
![Bildschirmfoto von 2021-09-20 10-26-36](https://user-images.githubusercontent.com/2373731/133975345-52a01e64-1ddb-4321-b9d7-a0b9ee054679.png)

Not only the attributes are in another color, but also the quotes, which makes the code much more readable.

Although the screenshot is from a Vue template (so not pure HTML), the same issue occurs within pure HTML files. Is there a way to make attributes more readable?

**Comment by patstockwell** [comment]
Hi @dubst3pp4, thanks for opening a git issue. I'll take a look and get back to you!

**Comment by patstockwell** [comment]
Hi @dubst3pp4, Thanks again for taking the time to request changes. I've added a few colour highlights to improve the html. Let me know what you think. `:PlugUpdate` should get you the latest (assuming you're using plug). See this commit -> 1e96ca23aefac8614658716f99bafbfad7726a1a

Specifically about the quotes, unfortunately, the html syntax file doesn't differentiate between the quotes and the content in between the quotes. They are both considered `htmlString`. In the screenshot you shared you will notice that line `476` in both images has the quotes and the string values as the same colour. The remaining attributes are actually an accident due to the fact that the html syntax file can't parse Vue syntax.

I hope these changes improve the readability. Generally, I try to stick to the way Sublime text does monokai as that was what inspired this project initially. See screenshots for comparisons.

### vim-monokai-tasty _before_
<img width="592" alt="Screen Shot 2021-09-22 at 9 03 04 pm" src="https://user-images.githubusercontent.com/14284552/134333545-445aef3b-c19b-44d5-882e-78ed1b78b260.png">

### vim-monokai-tasty _after_
<img width="585" alt="Screen Shot 2021-09-22 at 9 03 16 pm" src="https://user-images.githubusercontent.com/14284552/134333549-d4992b32-649e-4448-bdca-f3a2e030b961.png">

### Sublime text
<img width="686" alt="Screen Shot 2021-09-22 at 9 06 04 pm" src="https://user-images.githubusercontent.com/14284552/134333541-3cc28273-1c12-461e-aafb-2c7b2d0f3b6c.png">

### night-owl
*Notice here the strings and the quotes are the same colour
<img width="584" alt="Screen Shot 2021-09-22 at 9 05 34 pm" src="https://user-images.githubusercontent.com/14284552/134333555-0f56bf15-7de7-47b9-8dc8-d0443d65fe18.png">

**Comment by dubst3pp4** [comment]
Thanks @patstockwell, sorry for the late response. For standard HTML attributes it looks fine, but for "non-standard" attributes used with Vue (eg. something like `:value="foo"`) it still looks the same. Maybe it has something todo with the [vim-vue-plugin](https://github.com/leafOfTree/vim-vue-plugin) I'm using. But I don't now how it differs to the standard html syntax file and how syntax is defined there (sorry I'm not that deep into Vim plugins).
