### ISSUE TITLE
Matched operator doesn’t stand out

### ISSUE THREAD

**Issue by ryanolsonx** [patstockwell/vim-monokai-tasty#6]
It might be a personal preference but when I have my cursor on an operator, I like to be able to see its match easily. Currently, there’s only an underline. Any way we can change the fg color to make it stand out? 

Nice theme btw

**Comment by harababurel** [comment]
Take a look at 8144deee4aa74c6b3ddbb0799e726c1c2dc59725. I prefer having the matching operators in bold but you can also change the background color (`s:none`) into any of these:

 https://github.com/patstockwell/vim-monokai-tasty/blob/07731f94342b0420d465ea97e92dbc3632935de8/colors/vim-monokai-tasty.vim#L24-L43

**Comment by patstockwell** [comment]
Hi @ryanolsonx,
@harababurel recently created a PR that updated the matching paren so that it is both bold and highlighted. See how you like this setting :)
If you would further like to customise the highlight by changing the colour, you could try adding to your _.vimrc_ something like:
```
highlight MatchParen ctermfg=81 guifg=#62D8F1
```
This would make the colour light blue. A quick search for cterm colours should give you a list of 256 numbers that match a hex code. Hope this helps ☺️

**Comment by ryanolsonx** [comment]
Thank you!
